/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testDiceRoll() {
        int input = 5;
        int output = 5;
        assertEquals("we expect a length of 5",
                output,
                Library.roll(input).length);
    }

    @Test
    public void testContainsDuplicate() {
        int[] input1  = {5, 5, 0, 3};
        int[] input2 = {3, 5, 2, 4, 8, 2};
        int[] input3= {3, 5, 2, 4, 8};

        boolean output1 = true;
        boolean output2 = true;
        boolean output3 = false;
        assertTrue("Expected true", Library.containsDuplicates(input1));
        assertTrue("Expected true", Library.containsDuplicates(input2));
        assertFalse("Expected false", Library.containsDuplicates(input3));
    }

    @Test
    public void testAverage(){
        int[] input  = {4, 5, 6, 6, 5};
        int output = 5;
        assertEquals("Expected 13", output, Library.average(input));
    }

    @Test
    public void testLowestAverage() {
        int[][] input = {{3,4,5,6}, {2, 2, 7, 5, 4, 20}};
        int output = 4;
        int actual = Library.lowestAverage(input);

        assertEquals("Expected 4",output, actual);
    }

    @Test
    public void testTemperatureData() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        String expected = "High: 72\n" +
                "Low: 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69";
        String actual = Library.weatherData(weeklyMonthTemperatures);
        assertEquals(expected, actual);
    }

    @Test
    public void testTally(){
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        assertEquals("Bush", Library.tally(votes));
    }
}
