/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testDiceRoll() {
        int input = 5;
        int output = 5;
        assertEquals("we expect a length of 5",
                output,
                Library.roll(input).length);
    }

    @Test
    public void testContainsDuplicate() {
        int[] input1  = {5, 5, 0, 3};
        int[] input2 = {3, 5, 2, 4, 8, 2};
        int[] input3= {3, 5, 2, 4, 8};

        boolean output1 = true;
        boolean output2 = true;
        boolean output3 = false;
        assertTrue("Expected true", Library.containsDuplicates(input1));
        assertTrue("Expected true", Library.containsDuplicates(input2));
        assertFalse("Expected false", Library.containsDuplicates(input3));
    }

    @Test
    public void testAverage(){
        int[] input  = {4, 5, 6, 6, 5};
        int output = 5;
        assertEquals("Expected 13", output, Library.average(input));
    }

    @Test
    public void testLowestAverage() {
        int[][] input = {{3,4,5,6}, {2, 2, 7, 5, 4, 20}};
        int output = 4;
        int actual = Library.lowestAverage(input);

        assertEquals("Expected 4",output, actual);
    }
}
