/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import javax.lang.model.SourceVersion;
import java.sql.SQLOutput;
import java.util.Arrays;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static int[] roll(int rollTimes) {
        int[] rollResultArray = new int[rollTimes];
        for (int i = 0; i < rollTimes; i++){
            int rollResult = (int)((Math.random() * (6 - 1)) + 1);
            rollResultArray[i] = rollResult;
        }
        return rollResultArray;
    }

    public static boolean containsDuplicates(int[] numArray) {
        for (int i = 0; i < numArray.length; i++) {
            for (int j = 0; j < numArray.length; j++) {
                if (numArray[i] == numArray[j] && i != j) {
                    return true;
                }
            }
        }
        return false;
    }

    public static int average (int[] array) {
        int total = 0;
        for(int num : array){
            total += num;
        }
        return total/array.length;
    }

    public static int lowestAverage(int[][] array) {
        int[] averageArray = new int[array.length];
        for ( int i  = 0; i < array.length; i++) {
            int total = 0;
            int average = 0;

            for (int j = 0; j < array[i].length; j++){
                total += array[i][j];
            }
            average = total/array[i].length;
            averageArray[i] = average;
        }
        Arrays.sort(averageArray);
        return averageArray[0];
    }

}
